config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'components', to: 'pages#components'
  get 'account', to: 'account#account'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :cars, only: %i[index show new create update destroy] do
    scope module: :cars do
      resources :alerts, only: %i[index]
      resources :documents, only: %i[index new create]
    end
  end

  resources :alerts, only: %i[update], controller: 'cars/alerts'
  scope module: :cars do
    resources :documents, only: %i[destroy]
  end
  resources :garages, only: %i[index]
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  belongs_to :specification

  has_many :alerts,    dependent: :destroy
  has_many :documents, dependent: :destroy

  accepts_nested_attributes_for :alerts

  def redcount
    alerts.select do |alert|
      alert.due_date.present? && alert.due_date <= Date.today
    end
  end

  def yellowcount
    alerts.select do |alert|
      alert.due_date.present? && alert.due_date > Date.today && alert.due_date <= (Date.today + alert.alert_category.max_weeks.week)
    end
  end
end

app/controllers/cars/alerts_controller.rb
class Cars::AlertsController < ApplicationController
  def index
    # @alert_categories = AlertCategory.all

    @car = Car.find(params[:car_id])
    @alerts = @car.alerts
    @alerts = @alerts.order(due_date: :asc)
    @red_alerts = Array.new
    @yellow_alerts = Array.new
    @green_alerts = Array.new
  end

  def edit
    @alert = Alert.find(params[:id])
  end

  def update
    # byebug
    @alert = Alert.find(params[:id])
    @alert.update(alert_params)
    @alert.completed_at = Time.zone.parse(params[:completed_at])
    @alert.save
    if @alert.alert_category.name == "Vérification des pneus"
      @alert.due_date = @alert.completed_at + 2.weeks
    elsif @alert.alert_category.name == "Vérification des niveaux"
      @alert.due_date = @alert.completed_at + 4.weeks
    elsif @alert.alert_category.name == "Entretien"
      @alert.due_date = @alert.completed_at + 1.year
    elsif @alert.alert_category.name == "Contrôle technique"
      @alert.due_date = @alert.completed_at + 2.years
    end

    @alert.save
    redirect_to car_alerts_path(@alert.car)
  end

  private

  def alert_params
    params.require(:alert).permit(:completed_at, :completed)
  end
end

app/controllers/cars/documents_controller.rb
class Cars::DocumentsController < ApplicationController
  def index
    @car = Car.find(params[:car_id])
    @documents = @car.documents
    @document = Document.new
    # @pdfdocs = @documents.select { |document| File.extname("#{document}") == ".pdf"}
    # @imgdocs = @documents.select { |document| File.extname("#{document}") == ".png" || ".jpeg"}

  end

  def new
    # @document = Document.new
  end

  def create
    @document = Document.new(document_params)
    @car = Car.find(params[:car_id])
    @document.car = @car
    if @document.save
      redirect_to car_documents_path(@car), notice: 'Document has been added.'
    else
      render :index
    end
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to car_documents_path(@document.car)

  end

  private

  def document_params
    params.require(:document).permit(:name, :document)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :all_specs, only: [:new, :create]
  before_action :find_car, only: [:show, :update, :destroy]

  def index
    @cars = Car.all
  end

  def show
  end

  def update
    @car.update(car_params)
    respond_to do |format|
      format.html
      format.text { render partial: "components/cars/car_mileage", locals: { car: @car }, formats: [:html] }
    end

    # redirect_to
  end

  def new
    # @specifications = Specification.all
    @car = Car.new(car_params)
    @alert1 = @car.alerts.build
    @alert2 = @car.alerts.build

    @user = current_user

    if params[:query].present?
      @specifications = @specifications.where('make ILIKE ?', "%#{params[:query]}%").or(@specifications.where('model ILIKE ?', "%#{params[:query]}%")).or(@specifications.where('engine ILIKE ?', "%#{params[:query]}%"))
    end

    respond_to do |format|
      format.html
      format.text { render partial: 'components/cars/list', local: { specifications: @specifications, car: @car, alert1: @alert1, alert2: @alert2 }, formats: [:html] }
    end
  end

  def create

    @car = Car.new(car_params)
    @car.user = current_user
    @car.specification = Specification.find(params[:spec_id])
    @alert_categories = AlertCategory.all
    # Alerts creation
    @due_date_ct = Date.strptime(params[:date_ct] , '%Y-%m-%d')+2.years
    @due_date_et = Date.strptime(params[:date_et], '%Y-%m-%d')+1.year
    # @redalerts = car.alerts.map { |alert| alert.due_date <= Date.today }
    # @yellowalerts = car.alerts.map { |alert| alert.due_date <= Date.today+alert.alert_category.max_weeks.week}

    Alert.create(alert_category_id: @alert_categories.first[:id], car: @car, due_date: @due_date_ct, completed: false, completed_at: params[:date_ct] )
    Alert.create(alert_category_id: @alert_categories.second[:id], car: @car, due_date: @due_date_et, completed: false, completed_at: params[:date_et] )
    Alert.create(alert_category_id: @alert_categories.third[:id], car: @car, due_date: nil, completed: false, completed_at: nil )
    Alert.create(alert_category_id: @alert_categories.fourth[:id], car: @car, due_date: nil, completed: false, completed_at: nil )
    if @car.save
      redirect_to cars_path, notice: 'Car has been added.'

    else
      render :new
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_path
  end

  private

  def find_car
    @car = Car.find(params[:id])
  end

  def car_params
    return {} unless params.has_key?(:car)
    params.require(:car).permit(:number_plate, :mileage)
  end


  def alert_params
    params.require(:alert).permit(:completed_at)
  end

  def all_specs
    @specifications = Specification.all.order("make")
  end
end

app/views/cars/index.html.erb
<div class="my_vehicules_title">
  <h2 class="h2title" >Vos véhicules</h2>
</div>
<div class = "my_vehicule_list">
  <% current_user.cars.each do |car| %>

    <%= render 'components/cars/my_vehicule_card', car: car %>
  <%end%>
</div>

<div class="add-button d-flex justify-content-center">
  <%= link_to "Ajouter un véhicule", new_car_path, class: "button" %>
</div>

app/views/cars/new.html.erb
<div data-controller="search-car" class="listed_new_cars">
  <div class="new_car_input card-shadow">
    <h2>Recherchez votre véhicule</h2>
    <div class="form-search">
      <%= form_with url: new_car_path, method: :get, html: {
        data: { search_car_target: 'form' } } do |f| %>
        <div class="input-group mb-0">
            <%= f.text_field :query,
                            class: "form-control",
                            placeholder: 'Marque, modèle, année, moteur...',
                            value: params[:query],
                            data: { search_car_target: 'input',
                                    action:'keyup->search-car#update' } %>
          <span class="input-group-text pop-up-icon-search"><i class="fas fa-search pop-up-icon"></i></span>
        </div>
      <% end %>
    </div>
  </div>
  <%= render "components/cars/list", local: { specifications: @specifications, car: @car, alert1: @alert1, alert2: @alert2 } %>
</div>

app/views/cars/show.html.erb
<div class="sticker">
  <% if @car.redcount.count >= 1 %>
    <%= link_to car_alerts_path(params[:id]), class: "center-text" do %>
      <div class="red-alert card-shadow">
        <p class="txt-white"> <%= @car.redcount.count + @car.yellowcount.count %> </p>
        <i class="fas fa-exclamation-triangle"></i>
      </div>
    <% end %>
  <% elsif @car.yellowcount.count >= 1 %>
    <%= link_to car_alerts_path(params[:id]), class: "center-text" do %>
      <div class="yellow-alert card-shadow">
        <p class="txt-white"> <%= @car.yellowcount.count %> </p>
        <i class="fas fa-info-circle"></i>
      </div>
    <% end %>
  <% end %>
</div>

<!-- image de la voiture et les spécification principal -->
<div class="car-tile">

  <% if @car.specification.photo.attached? %>
    <%= cl_image_tag @car.specification.photo.key%>
  <% end %>

  <div class="car-tile-info tile-shadow">
    <h2><%= @car.specification.make%> <strong><%= @car.specification.model%></strong></h2>
    <p><%= @car.specification.engine%></p>
  </div>

  <!-- kilométrage du véhicule + update -->
  <div data-controller="mileage-update">

    <div  class="car-tile-mileage tile-shadow" data-mileage-update-target="tile">
      <%= render 'components/cars/car_mileage', car: @car %>
      <div  type="button" class="button-mileage"
            data-action="click->mileage-update#displayForm">
        <i class="fas fa-pen"></i>
      </div>
    </div>

    <div  class="car-tile-mileage-update tile-shadow d-none" data-mileage-update-target="formContainer">
      <%= form_for @car, html: {class: 'mileage-form', 'data-mileage-update-target': 'form', 'data-action': 'submit->mileage-update#submit'} do |f| %>
        <div class="mileage-group">
          <%= f.text_field :mileage, class: "mileage-input" %>
          <p>Km</p>
        </div>
        <div class="mileage-group">
          <button type="button" class="button-mileage-cancel" data-action="click->mileage-update#hideForm">
            <i class="fas fa-times"></i>
          </button>
          <%= button_tag type: 'submit', class:"button-mileage" do %>
            <i class="fas fa-check" aria-hidden="true"></i>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>

</div>


<div class="car-tile-buttons">

  <%= link_to car_alerts_path(params[:id]), class: "center-text" do %>
    <i class="fas fa-bell"></i>
    <p class="txt-white">Rappels</p>
  <% end %>

  <%= link_to car_documents_path(params[:id]), class: "center-text" do %>
    <i class="fas fa-file-alt"></i>
    <p class="txt-white">Documents</p>
  <% end %>

</div>


<div class="info-tile">

  <h2>Informations clés</h2>

  <div class="key-info">
    <p>Immatriculation</p>
    <p class="txt-gold"><%= @car.number_plate %></p>
  </div>
  <hr>

  <div class="key-info">
    <p>Carburant</p>
    <p class="txt-gold"><%= @car.specification.fuel %></p>
  </div>
  <hr>

  <div class="key-info">
    <p>Boîte</p>
    <p class="txt-gold"><%= @car.specification.transmission %></p>
  </div>
  <hr>

  <div class="key-info">
    <p>Crit'Air</p>
    <p class="txt-gold"><%= @car.specification.critair %></p>
  </div>

</div>


<!-- suppression du véhicule -->

<div class="delete-car">
  <%= render 'components/cars/modal_car_delete', car: @car %>
</div>