config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'components', to: 'pages#components'
  get 'account', to: 'account#account'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :cars, only: %i[index show new create update destroy] do
    scope module: :cars do
      resources :alerts, only: %i[index]
      resources :documents, only: %i[index new create]
    end
  end

  resources :alerts, only: %i[update], controller: 'cars/alerts'
  scope module: :cars do
    resources :documents, only: %i[destroy]
  end
  resources :garages, only: %i[index]
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  belongs_to :specification

  has_many :alerts,    dependent: :destroy
  has_many :documents, dependent: :destroy

  accepts_nested_attributes_for :alerts

  def redcount
    alerts.select do |alert|
      alert.due_date.present? && alert.due_date <= Date.today
    end
  end

  def yellowcount
    alerts.select do |alert|
      alert.due_date.present? && alert.due_date > Date.today && alert.due_date <= (Date.today + alert.alert_category.max_weeks.week)
    end
  end
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :car
  has_one_attached :document
end

app/controllers/cars/alerts_controller.rb
class Cars::AlertsController < ApplicationController
  def index
    # @alert_categories = AlertCategory.all

    @car = Car.find(params[:car_id])
    @alerts = @car.alerts
    @alerts = @alerts.order(due_date: :asc)
    @red_alerts = Array.new
    @yellow_alerts = Array.new
    @green_alerts = Array.new
  end

  def edit
    @alert = Alert.find(params[:id])
  end

  def update
    # byebug
    @alert = Alert.find(params[:id])
    @alert.update(alert_params)
    @alert.completed_at = Time.zone.parse(params[:completed_at])
    @alert.save
    if @alert.alert_category.name == "Vérification des pneus"
      @alert.due_date = @alert.completed_at + 2.weeks
    elsif @alert.alert_category.name == "Vérification des niveaux"
      @alert.due_date = @alert.completed_at + 4.weeks
    elsif @alert.alert_category.name == "Entretien"
      @alert.due_date = @alert.completed_at + 1.year
    elsif @alert.alert_category.name == "Contrôle technique"
      @alert.due_date = @alert.completed_at + 2.years
    end

    @alert.save
    redirect_to car_alerts_path(@alert.car)
  end

  private

  def alert_params
    params.require(:alert).permit(:completed_at, :completed)
  end
end

app/controllers/cars/documents_controller.rb
class Cars::DocumentsController < ApplicationController
  def index
    @car = Car.find(params[:car_id])
    @documents = @car.documents
    @document = Document.new
    # @pdfdocs = @documents.select { |document| File.extname("#{document}") == ".pdf"}
    # @imgdocs = @documents.select { |document| File.extname("#{document}") == ".png" || ".jpeg"}

  end

  def new
    # @document = Document.new
  end

  def create
    @document = Document.new(document_params)
    @car = Car.find(params[:car_id])
    @document.car = @car
    if @document.save
      redirect_to car_documents_path(@car), notice: 'Document has been added.'
    else
      render :index
    end
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to car_documents_path(@document.car)

  end

  private

  def document_params
    params.require(:document).permit(:name, :document)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :all_specs, only: [:new, :create]
  before_action :find_car, only: [:show, :update, :destroy]

  def index
    @cars = Car.all
  end

  def show
  end

  def update
    @car.update(car_params)
    respond_to do |format|
      format.html
      format.text { render partial: "components/cars/car_mileage", locals: { car: @car }, formats: [:html] }
    end

    # redirect_to
  end

  def new
    # @specifications = Specification.all
    @car = Car.new(car_params)
    @alert1 = @car.alerts.build
    @alert2 = @car.alerts.build

    @user = current_user

    if params[:query].present?
      @specifications = @specifications.where('make ILIKE ?', "%#{params[:query]}%").or(@specifications.where('model ILIKE ?', "%#{params[:query]}%")).or(@specifications.where('engine ILIKE ?', "%#{params[:query]}%"))
    end

    respond_to do |format|
      format.html
      format.text { render partial: 'components/cars/list', local: { specifications: @specifications, car: @car, alert1: @alert1, alert2: @alert2 }, formats: [:html] }
    end
  end

  def create

    @car = Car.new(car_params)
    @car.user = current_user
    @car.specification = Specification.find(params[:spec_id])
    @alert_categories = AlertCategory.all
    # Alerts creation
    @due_date_ct = Date.strptime(params[:date_ct] , '%Y-%m-%d')+2.years
    @due_date_et = Date.strptime(params[:date_et], '%Y-%m-%d')+1.year
    # @redalerts = car.alerts.map { |alert| alert.due_date <= Date.today }
    # @yellowalerts = car.alerts.map { |alert| alert.due_date <= Date.today+alert.alert_category.max_weeks.week}

    Alert.create(alert_category_id: @alert_categories.first[:id], car: @car, due_date: @due_date_ct, completed: false, completed_at: params[:date_ct] )
    Alert.create(alert_category_id: @alert_categories.second[:id], car: @car, due_date: @due_date_et, completed: false, completed_at: params[:date_et] )
    Alert.create(alert_category_id: @alert_categories.third[:id], car: @car, due_date: nil, completed: false, completed_at: nil )
    Alert.create(alert_category_id: @alert_categories.fourth[:id], car: @car, due_date: nil, completed: false, completed_at: nil )
    if @car.save
      redirect_to cars_path, notice: 'Car has been added.'

    else
      render :new
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_path
  end

  private

  def find_car
    @car = Car.find(params[:id])
  end

  def car_params
    return {} unless params.has_key?(:car)
    params.require(:car).permit(:number_plate, :mileage)
  end


  def alert_params
    params.require(:alert).permit(:completed_at)
  end

  def all_specs
    @specifications = Specification.all.order("make")
  end
end

app/views/cars/documents/_delete_document_modal.html.erb
<i class="fas fa-trash-alt button-circle-doc" data-bs-toggle="modal" data-bs-target="#docDelete"></i>
<!-- Modal -->
<div class="modal fade" id="docDelete" tabindex="-1" aria-labelledby="docDeleteLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title" id="docDeleteLabel">Supprimer votre véhicule</h2>
      </div>
      <div class="modal-body">
        <p>
          Voulez-vous vraiment supprimer votre document ?
        </p>
      </div>
      <div class="modal-footer">
        <%= link_to "supprimer",
            document_path(document),
            method: :delete,
            class: "button-outline"%>
          <button type="button" class="button" data-bs-dismiss="modal" aria-label="Close">Annuler</button>
      </div>
    </div>
  </div>
</div>

app/views/cars/documents/index.html.erb
<div class="alert-return-link tile-shadow">
    <div class="d-flex">
      <%= link_to "", car_path(@car), class: "fas fa-angle-left return-icon-alert" %>
      <%= link_to "Retour au véhicule", car_path(@car), class: "return-text"  %>
    </div>
  </div>

<div class="documents_list">
  <% @documents.each do |document| %>
    <div class="document_card d-flex rounded-card">
      <div>
        <strong class="doc-name"><%= document.name%></strong>
        <p class="txt-info"><%= document.created_at.strftime("ajouté le %m/%Y") %></p>
      </div>
      <div class="document_actions d-flex">
        <a href="<%=download_link(cl_image_path(document.document.key))%>"><i class="fas fa-download button-circle-doc document_icon"></i></a>
        <%= render 'cars/documents/delete_document_modal', document: document %>
      </div>
    </div>
<% end %>
</div>


<div class="d-flex justify-content-center">
  <button type="button" class="button" data-bs-toggle="modal" data-bs-target="#documentModal">
    Ajouter un document
  </button>
</div>

<!-- Modal -->
<div class="modal fade" id="documentModal" tabindex="-1" aria-labelledby="documentModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="documentModalLabel">Ajouter un document</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for([@car, @document]) do |f| %>
          <%= f.input :name, as: :string, label: "Nom du document", class: "txt-p" %>
          <%= f.input :document, as: :file, class: "txt-p" %>
          <%= f.submit "Ajouter", class: "btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>